In [7]:
import numpy as np

In [8]:
a = np.arange(6).reshape(2,3)

b = np.arange(5,-1,-1).reshape(2,3)
f = np.array([[0,5,1],[4,2,3]]).reshape(2,3)
print("a val")
print(a)
print('no axis')
print(np.argmax(a))
print('axis 0')
print(np.argmax(a, axis=0))
print('axis 1')
print(np.argmax(a, axis=1))
print()
print("b val")
print(b)
print('no axis')
print(np.argmax(b))
print('axis 0')
print(np.argmax(b, axis=0))
print('axis 1')
print(np.argmax(b, axis=1))
print("f val")
print(f)
print('no axis')
print(np.argmax(f))
print('axis 0')
print(np.argmax(f, axis=0))
print('axis 1')
print(np.argmax(f, axis=1))
print()
# 3 dimensions

c = np.arange(12).reshape(2,3,2)

d = np.arange(12,0,-1).reshape(2,3,2)
print()
print("c val")
print(c)
print('no axis')
print(np.argmax(c))
print('axis 0')
print(np.argmax(c, axis=0))
print('axis 1')
print(np.argmax(c, axis=1))
print()
print("d val")
print(d)
print('no axis')
print(np.argmax(d))
print('axis 0')
print(np.argmax(d, axis=0))
print('axis 1')
print(np.argmax(d, axis=1))

# summing along axis
print("")
print("Summing")
print("a val")
print(a)
print('no axis')
print(np.sum(a))
print('axis 0')
print(np.sum(a, axis=0))
print('axis 1')
print(np.sum(a, axis=1))
print()
print("b val")
print(b)
print('no axis')
print(np.sum(b))
print('axis 0')
print(np.sum(b, axis=0))
print('axis 1')
print(np.sum(b, axis=1))
print("f val")
print(f)
print('no axis')
print(np.sum(f))
print('axis 0')
print(np.sum(f, axis=0))
print('axis 1')
print(np.sum(f, axis=1))
print()

a val
[[0 1 2]
 [3 4 5]]
no axis
5
axis 0
[1 1 1]
axis 1
[2 2]

b val
[[5 4 3]
 [2 1 0]]
no axis
0
axis 0
[0 0 0]
axis 1
[0 0]
f val
[[0 5 1]
 [4 2 3]]
no axis
1
axis 0
[1 0 1]
axis 1
[1 0]


c val
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]
no axis
11
axis 0
[[1 1]
 [1 1]
 [1 1]]
axis 1
[[2 2]
 [2 2]]

d val
[[[12 11]
  [10  9]
  [ 8  7]]

 [[ 6  5]
  [ 4  3]
  [ 2  1]]]
no axis
0
axis 0
[[0 0]
 [0 0]
 [0 0]]
axis 1
[[0 0]
 [0 0]]

Summing
a val
[[0 1 2]
 [3 4 5]]
no axis
15
axis 0
[3 5 7]
axis 1
[ 3 12]

b val
[[5 4 3]
 [2 1 0]]
no axis
15
axis 0
[7 5 3]
axis 1
[12  3]
f val
[[0 5 1]
 [4 2 3]]
no axis
15
axis 0
[4 7 4]
axis 1
[6 9]



In [3]:
import sys
print(sys.version)

3.6.4 (default, Jan 11 2018, 13:44:21) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]
