In [1]:
import numpy as np

A = np.array( [[1,1],
            [0,1]] )
B = np.array( [[2,0],
            [3,4]] )
print(A*B)                         # elementwise product


A.dot(B)                    # matrix product


print(np.dot(A, B))                # another matrix product

[[2 0]
 [0 4]]
[[5 4]
 [3 4]]


In [2]:
#show regular product only works if same dimensions
#http://docs.scipy.org/doc/numpy/user/basics.broadcasting.html
C = np.array( [[1,1,7,2],
            [0,1,8,1]] )
D = np.array( [[2,0],
            [3,4]] )
C*D #error expected

ValueError: operands could not be broadcast together with shapes (2,4) (2,2) 

In [7]:
#http://docs.scipy.org/doc/numpy/user/basics.broadcasting.html
C = np.array( [[1,1,7,2],
            [0,1,8,1]] )
D = np.array( [[2]] )
C*D

array([[ 2,  2, 14,  4],
       [ 0,  2, 16,  2]])