In [3]:
import numpy as np
import tensorflow as tf


In [4]:
a = (np.random.rand(6).astype(np.float32)*10).round()

In [5]:
print(a)

[ 1.  4.  3.  4.  1.  4.]


In [6]:
b = a.reshape(2, 3).astype(np.int32)
print(b)

[[1 4 3]
 [4 1 4]]


In [7]:
#show how reduce mean collapses the targeted index
br = tf.reduce_mean(b.astype(np.float32),reduction_indices=[0])
br2 = tf.reduce_mean(b.astype(np.float32),reduction_indices=[1])
print(b)
print(b.shape)
with tf.Session() as sess: #automatically closes session up leaving block
  result = sess.run([br,br2])
  print(result[0])
  print(result[1])
  print(result[0].shape) #br shape
  print(result[1].shape) #br2 shape
# explicitly close session with sess.close()

[[1 4 3]
 [4 1 4]]
(2, 3)
[ 2.5  2.5  3.5]
[ 2.66666675  3.        ]
(3,)
(2,)


In [8]:
# just looking at some Variable features including shapes.
x = tf.ones([3, 25])
W = tf.ones([25, 5])
b = tf.ones([5])
xW = tf.matmul(x,W); #dot product aka "matrix multiply"
xWplusb = xW+b
print(x)
print(W)
print(b)
with tf.Session() as sess:
    result = sess.run([x,W,b,xW,xWplusb])
    print(result[0])
    print(result[0].shape)
    print()
    print(result[1])
    print(result[1].shape)
    print()
    print(result[2])
    print(result[2].shape)
    print()
    print(result[3])
    print(result[3].shape)
    print()
    print(result[4])
    print(result[4].shape) 


Tensor("ones:0", shape=(3, 25), dtype=float32)
Tensor("ones_1:0", shape=(25, 5), dtype=float32)
Tensor("ones_2:0", shape=(5,), dtype=float32)
[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
   1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
   1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
   1.  1.  1.  1.  1.  1.  1.]]
(3, 25)

[[ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1