In [1]:
import numpy as np
import tensorflow as tf


In [2]:
# just looking at some Variable features including shapes.
x = tf.ones([3, 25])
W = tf.ones([25, 5])
b = tf.ones([5])
xW = tf.matmul(x,W); #dot product aka "matrix multiply"
xWplusb = xW+b
with tf.Session() as sess:
    result = sess.run([x,W,b,xW,xWplusb])
    print(result[0])
    print(result[0].shape)
    print()
    print(result[1])
    print(result[1].shape)
    print()
    print(result[2])
    print(result[2].shape)
    print()
    print(result[3])
    print(result[3].shape)
    print()
    print(result[4])
    print(result[4].shape) 


[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
   1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
   1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
   1.  1.  1.  1.  1.  1.  1.]]
(3, 25)

[[ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]]
(25, 5)

[ 1.  1.  1.  1.  1.]
(5,)

[[ 25.  25.  25.  25.  25.]
 [ 25.  25.  25.  25.  25.]
 [ 25.