In [1]:
import tensorflow as tf
import numpy as np

/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)


In [2]:

# don't understand how this 3d array resolves along axis == 1with argmax 
am_in_3d = np.array([[[5,1],[3,6],[5,999],[1,3],[4,1000]]]).astype(np.float32) 
# numpy version of argmax = http://docs.scipy.org/doc/numpy-1.10.1/reference/generated/numpy.argmax.html
#am_in = np.array([[1,3,7,0,0]]).astype(np.float32)

# (below) with respect to am_in, if target_axis == 1 then argmax returns the highest value for each axis=1
# in the below case there are 3 arrays for axis ==1 so there will be 3 high values [7,9,30] which have indexes [2,4,0]
am_in = np.array([[1,3,7,0,0],[1,3,7,0,9],[30,3,7,0,9]]).astype(np.float32)



#am_in = np.array([1,3,7,0,9]).astype(np.float32)
'''
am_in = np.array(
    [
        [[17,0],[10,6],[2,2],[50,41],[1,90]],
        [[0,0],[5,8],[47,2],[8,6],[1,2]]
    ]
).astype(np.float32)
'''
target_axis = 1
#sum_am_in = am_in.sum(axis=target_axis)
print(am_in)

print(am_in.shape)
print()
print(am_in_3d)

print(am_in_3d.shape)
print("finding largest value index along axis/dimension " + str(target_axis))

ph_am = tf.placeholder(tf.float32, am_in.shape)
ph_am_3d = tf.placeholder(tf.float32, am_in_3d.shape)
print(ph_am);
print(ph_am_3d);

am = tf.argmax(ph_am,target_axis) #https://www.tensorflow.org/versions/r0.8/api_docs/python/math_ops.html#argmax
am_3d = tf.argmax(ph_am_3d,target_axis)
#dimension == axis ?
# argmax Returns the INDEX (not the value) with the largest value across dimensions of a tensor.

[[ 1.  3.  7.  0.  0.]
 [ 1.  3.  7.  0.  9.]
 [30.  3.  7.  0.  9.]]
(3, 5)

[[[   5.    1.]
  [   3.    6.]
  [   5.  999.]
  [   1.    3.]
  [   4. 1000.]]]
(1, 5, 2)
finding largest value index along axis/dimension 1
Tensor("Placeholder:0", shape=(3, 5), dtype=float32)
Tensor("Placeholder_1:0", shape=(1, 5, 2), dtype=float32)


In [3]:
with tf.Session() as sess: #automatically closes session up leaving block
  print (sess.run(am,feed_dict={ph_am: am_in}))
  print()
  print (sess.run(am_3d,feed_dict={ph_am_3d: am_in_3d}))

# explicitly close session with sess.close()

[2 4 0]

[[0 4]]
