In [2]:
from __future__ import print_function
import mxnet as mx
import mxnet.ndarray as nd
import math

RuntimeError: module compiled against API version 0xc but this version of numpy is 0xb

RuntimeError: module compiled against API version 0xc but this version of numpy is 0xb

In [3]:
# https://mxnet.apache.org/api/python/ndarray/ndarray.html?highlight=norm#mxnet.ndarray.norm
x = [[1, 2],
     [3, 4]]
nd_x = nd.array(x)
print(nd.norm(nd_x))
# above same as
print (math.sqrt( 1**2 + 2**2 + 3**2 + 4**2))

nx_x2 = nd.array([(math.sqrt(2)/2),(math.sqrt(2)/2)]) # a^2 + b^2 = c^2 for a 90 x 45 x 45 degree triangle
print(nd.norm(nd_x))

#trying to understand is use on http://gluon.mxnet.io/chapter02_supervised-learning/perceptron.html#A-Separable-Classification-Problem
print(nd_x / nd.norm(nd_x))


[ 5.47722578]
<NDArray 1 @cpu(0)>
5.477225575051661

[ 5.47722578]
<NDArray 1 @cpu(0)>

[[ 0.18257418  0.36514837]
 [ 0.54772252  0.73029673]]
<NDArray 2x2 @cpu(0)>


In [4]:
#random
dims =2
a = nd.random_normal(shape=(dims))
print(a)
print(a.shape)
b = nd.random_normal(shape=(1,2))
print(b)
print(b.shape)


[ 1.16307867  0.48380461]
<NDArray 2 @cpu(0)>
(2,)

[[ 0.29956347  0.15302546]]
<NDArray 1x2 @cpu(0)>
(1, 2)


In [8]:
def dropout(X, drop_probability):
    keep_probability = 1 - drop_probability
    nd_rand_uni = nd.random_uniform(0, 1.0, X.shape, ctx=X.context)
    print(nd_rand_uni)
    print(keep_probability)
    mask = nd_rand_uni < keep_probability
    print(mask)
    #############################
    #  Avoid division by 0 when scaling
    #############################
    if keep_probability > 0.0:
        scale = (1/keep_probability)
    else:
        scale = 0.0
    return mask * X * scale


A = nd.arange(20).reshape((5,4))
dropout(A, 0.0)
dropout(A, 0.5)
dropout(A, 1.0)


[[ 0.73926359  0.01998767  0.03918779  0.44171092]
 [ 0.28280696  0.97958672  0.12019657  0.35944447]
 [ 0.29614019  0.48089352  0.11872771  0.68866116]
 [ 0.31798318  0.88047588  0.41426298  0.91823548]
 [ 0.0641475   0.21682213  0.6924721   0.56518888]]
<NDArray 5x4 @cpu(0)>
1.0

[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]
<NDArray 5x4 @cpu(0)>

[[ 0.56660146  0.86510259  0.2653895   0.50896895]
 [ 0.52324808  0.91672295  0.0939405   0.9211576 ]
 [ 0.57594651  0.08311249  0.9292962   0.27771857]
 [ 0.31856894  0.0093567   0.66741037  0.84234208]
 [ 0.13179787  0.64717412  0.71632719  0.84138614]]
<NDArray 5x4 @cpu(0)>
0.5

[[ 0.  0.  1.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  1.  0.  1.]
 [ 1.  1.  0.  0.]
 [ 1.  0.  0.  0.]]
<NDArray 5x4 @cpu(0)>

[[ 0.28940609  0.26473016  0.18319136  0.39782074]
 [ 0.58651292  0.55282146  0.02010755  0.16494046]
 [ 0.82894003  0.36980811  0.00469548  0.14644176]
 [ 0.67781651  0.5696184   0.27000797  0.7


[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
<NDArray 5x4 @cpu(0)>