In [2]:
# http://gluon.mxnet.io/chapter01_crashcourse/ndarray.html
# https://mxnet.apache.org/tutorials/index.html
import mxnet as mx
from mxnet import nd
mx.random.seed(1)
# just looking at shapes


# empty array no init
x = nd.empty((3, 4))
print(x)

# empty but with with init

x = nd.zeros((3, 4), mx.cpu(0))
print(x)
x = nd.ones((3, 4), mx.cpu(0))
print(x)


# random with normal distribution and zero mean
print("\nshape = (3,4)");
y = nd.random_normal(0, 1, shape=(3, 4))
print(y);

print("\nshape = 3");
# random with normal distribution and zero mean - different shape
y2 = nd.random_normal(0, 1, shape=3)
print(y2);

print("\nshape = (3,1)");
# random with normal distribution and zero mean - different shape #2
y3 = nd.random_normal(0, 1, shape=(3,1))
print(y3);

print("\nshape = (1,3)");
# random with normal distribution and zero mean - different shape #3
y4 = nd.random_normal(0, 1, shape=(1,3))
print(y4);
print();

# convert ndarray to numpy

yn = y.asnumpy()
print(yn)
print(type(yn))




[[  0.00000000e+00  -0.00000000e+00   0.00000000e+00  -0.00000000e+00]
 [  4.20389539e-45   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   2.75506488e-40]]
<NDArray 3x4 @cpu(0)>

[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
<NDArray 3x4 @cpu(0)>

[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]
<NDArray 3x4 @cpu(0)>

shape = (3,4)

[[ 0.03629481 -0.49024421 -0.95017916  0.03751944]
 [-0.72984636 -2.04010558  1.482131    1.04082799]
 [-0.45256865  0.31160426 -0.83673781 -0.78830057]]
<NDArray 3x4 @cpu(0)>

shape = 3

[ 0.12664476 -0.17841923  0.76479203]
<NDArray 3 @cpu(0)>

shape = (3,1)

[[-0.21776067]
 [ 2.22578788]
 [-0.68832648]]
<NDArray 3x1 @cpu(0)>

shape = (1,3)

[[ 0.84155577 -0.61584121  0.01961165]]
<NDArray 1x3 @cpu(0)>

[[ 0.03629481 -0.49024421 -0.95017916  0.03751944]
 [-0.72984636 -2.04010558  1.482131    1.04082799]
 [-0.45256865  0.31160426 -0.83673781 -0.78830057]]
<class 'numpy.ndarray'

In [3]:
# get array metadata/info

#shape and size
print(y.shape)
print(y.size)

(3, 4)
12


In [4]:
# ndarray Operations
print(x)
print(y)
z = nd.ones(shape=(4,), ctx=mx.cpu(0))+4 
print(z)
#mult and addition
print(x + y) 
print(x*y) # element-wise multiplication
# addition with different shapes
print(y + z) 

# max
print("\n y max axis 1")
print(nd.max(y,axis=1))
print("\n y max axis 0")
print(nd.max(y,axis=0))

# exponentiation?
print("\n\n y exponentiation \n")
print(nd.exp(y))

# dot product
print("\ny orignal\n")
print(y)
print("\ny is transposed\n")
print(y.T)

print("\nMultiplication of\n")
print(x,y.T)

print("\nDot Product of x and y.T == \n")
print(nd.dot(x, y.T)) #y is transposed, See https://en.wikipedia.org/wiki/Transpose



[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]
<NDArray 3x4 @cpu(0)>

[[ 0.03629481 -0.49024421 -0.95017916  0.03751944]
 [-0.72984636 -2.04010558  1.482131    1.04082799]
 [-0.45256865  0.31160426 -0.83673781 -0.78830057]]
<NDArray 3x4 @cpu(0)>

[ 5.  5.  5.  5.]
<NDArray 4 @cpu(0)>

[[ 1.03629482  0.50975579  0.04982084  1.03751945]
 [ 0.27015364 -1.04010558  2.482131    2.04082799]
 [ 0.54743135  1.31160426  0.16326219  0.21169943]]
<NDArray 3x4 @cpu(0)>

[[ 0.03629481 -0.49024421 -0.95017916  0.03751944]
 [-0.72984636 -2.04010558  1.482131    1.04082799]
 [-0.45256865  0.31160426 -0.83673781 -0.78830057]]
<NDArray 3x4 @cpu(0)>

[[ 5.03629494  4.50975561  4.0498209   5.03751945]
 [ 4.27015352  2.95989442  6.482131    6.04082775]
 [ 4.54743147  5.3116045   4.16326237  4.21169949]]
<NDArray 3x4 @cpu(0)>

 y max axis 1

[ 0.03751944  1.482131    0.31160426]
<NDArray 3 @cpu(0)>

 y max axis 0

[ 0.03629481  0.31160426  1.482131    1.04082799]
<NDArray 4 @cpu(0)>


 y exponen

In [5]:
# data sum
data = nd.array([[[1,2],[2,3],[1,3]],
        [[1,4],[4,3],[5,2]],
        [[7,1],[7,2],[7,3]]])
print(data.shape)
print(data)
print("\naxis 2")
print(nd.sum(data, axis=2))
print("\naxis 1")
print(nd.sum(data, axis=1))
print("\naxis 0")
print(nd.sum(data, axis=0))
print("\naxis NULL")
print(nd.sum(data))

(3, 3, 2)

[[[ 1.  2.]
  [ 2.  3.]
  [ 1.  3.]]

 [[ 1.  4.]
  [ 4.  3.]
  [ 5.  2.]]

 [[ 7.  1.]
  [ 7.  2.]
  [ 7.  3.]]]
<NDArray 3x3x2 @cpu(0)>

axis 2

[[  3.   5.   4.]
 [  5.   7.   7.]
 [  8.   9.  10.]]
<NDArray 3x3 @cpu(0)>

axis 1

[[  4.   8.]
 [ 10.   9.]
 [ 21.   6.]]
<NDArray 3x2 @cpu(0)>

axis 0

[[  9.   7.]
 [ 13.   8.]
 [ 13.   8.]]
<NDArray 3x2 @cpu(0)>

axis NULL

[ 58.]
<NDArray 1 @cpu(0)>


In [5]:
# in-place operations


#show how memory address changes

print('id(y):', id(y))
y = y + x
print('id(y):', id(y))

# use [:] syntax to prevent new address

print('id(y):', id(y))
y[:] = x + y
print('id(y):', id(y))

# event better with memory

nd.elemwise_add(x, y, out=y)

id(y): 4533467680
id(y): 4551093832
id(y): 4551093832
id(y): 4551093832



[[ 3.03629494  2.50975585  2.0498209   3.03751945]
 [ 2.27015352  0.95989442  4.482131    4.04082775]
 [ 2.54743147  3.31160426  2.16326213  2.21169949]]
<NDArray 3x4 @cpu(0)>

In [6]:
# Slicing

print(x)
print(x[1:3])
print(x)
x[1,2] = 9.0
print(x)


[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]
<NDArray 3x4 @cpu(0)>

[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]
<NDArray 2x4 @cpu(0)>

[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]
<NDArray 3x4 @cpu(0)>

[[ 1.  1.  1.  1.]
 [ 1.  1.  9.  1.]
 [ 1.  1.  1.  1.]]
<NDArray 3x4 @cpu(0)>


In [7]:
# Broadcasting
# see http://gluon.mxnet.io/chapter01_crashcourse/ndarray.html#Broadcasting

x = nd.ones(shape=(3,3))
print('x = ', x)
y = nd.arange(3)
print('y = ', y)
print('x + y = ', x + y)

# Broadcast prefers to duplicate along the left most axis
# axis definition https://docs.scipy.org/doc/numpy-1.13.0/glossary.html
# http://gluon.mxnet.io/chapter01_crashcourse/linear-algebra.html#Length,-dimensionality,-and,-shape

y = y.reshape((3,1))
print('y = ', y)
print('x + y = ', x+y)

x =  
[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]
<NDArray 3x3 @cpu(0)>
y =  
[ 0.  1.  2.]
<NDArray 3 @cpu(0)>
x + y =  
[[ 1.  2.  3.]
 [ 1.  2.  3.]
 [ 1.  2.  3.]]
<NDArray 3x3 @cpu(0)>
y =  
[[ 0.]
 [ 1.]
 [ 2.]]
<NDArray 3x1 @cpu(0)>
x + y =  
[[ 1.  1.  1.]
 [ 2.  2.  2.]
 [ 3.  3.  3.]]
<NDArray 3x3 @cpu(0)>


In [8]:
# context
#http://gluon.mxnet.io/chapter01_crashcourse/ndarray.html#Managing-context

# run on first gpu
# z = nd.ones(shape=(3,3), ctx=mx.gpu(0)) #doesn't work on osx without cuda and built from source
# run on first cpu
z = nd.ones(shape=(3,3), ctx=mx.cpu(0)) 
print(z)

# copy var and its context

x_cpu = x.copyto(mx.cpu(0))
print(x_cpu)

# show context

print(x_cpu.context)
print(z.context)

#!!! In order to perform an operation on two ndarrays x1 and x2, we need them both to live on the same context


[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]
<NDArray 3x3 @cpu(0)>

[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]
<NDArray 3x3 @cpu(0)>
cpu(0)
cpu(0)


In [12]:
penalty = nd.ones(shape=2)
print(penalty)
print(penalty + y)


[ 1.  1.]
<NDArray 2 @cpu(0)>

[[ 1.  1.]
 [ 2.  2.]
 [ 3.  3.]]
<NDArray 3x2 @cpu(0)>


In [10]:
# random shapes
# http://gluon.mxnet.io/chapter04_convolutional-neural-networks/cnn-scratch.html#Parameters
print(nd.random_normal(0, 1, shape=(7, 1, 3,3)))
# print(nd.random_normal(0, 1, shape=(7, 3,3)))
print(nd.random_normal(0, 1, shape=(7, 2, 3,3)))


[[[[-1.30455256 -0.04083065 -0.7021268 ]
   [ 0.41314802 -0.83476329 -1.22061241]
   [-1.5813998  -0.24973103 -0.31050238]]]


 [[[ 0.48244068  1.09116614 -0.83994013]
   [-0.39747313 -0.25414369 -1.1389668 ]
   [ 0.5165205  -0.81573743  0.12702422]]]


 [[[ 0.59272307  1.63542664  0.46400866]
   [ 1.62629163  2.24216223  1.02091455]
   [-1.09018636 -0.37763306 -2.09041286]]]


 [[[-1.62223935 -0.83152634 -1.14183044]
   [ 0.32903334  1.48399293  0.53581762]
   [-0.35518879  0.24801721 -1.24852252]]]


 [[[ 1.0230037   1.22176135 -0.66383916]
   [-0.63390923 -0.35884881  2.77550817]
   [-0.44805381 -0.13958028 -1.25936031]]]


 [[[-0.38506052 -1.99846768  0.24923693]
   [ 0.33445987 -0.0267263  -2.33836484]
   [ 0.17879342 -1.32376277 -0.13077155]]]


 [[[-1.81571937  0.84184343  2.23764229]
   [-0.13346899 -0.3898634   0.90282428]
   [-0.83114076 -0.7304737   0.43580166]]]]
<NDArray 7x1x3x3 @cpu(0)>

[[[[ 0.26920113 -1.98025572 -0.9068836 ]
   [-0.45799196 -0.32951903 -0.45696434]
  