In [2]:
# http://gluon.mxnet.io/chapter01_crashcourse/ndarray.html
# https://mxnet.apache.org/tutorials/index.html
import mxnet as mx
from mxnet import nd
mx.random.seed(1)
# just looking at shapes


# empty array no init
x = nd.empty((3, 4))
print(x)

# empty but with with init

x = nd.zeros((3, 4), mx.cpu(0))
print(x)
x = nd.ones((3, 4), mx.cpu(0))
print(x)


# random with normal distribution and zero mean
y = nd.random_normal(0, 1, shape=(3, 4))
print(y);

# convert ndarray to numpy

yn = y.asnumpy()
print(yn)
print(type(yn))




[[0.0000000e+00 1.0842022e-19 0.0000000e+00 1.0842022e-19]
 [4.2038954e-45 0.0000000e+00 0.0000000e+00 0.0000000e+00]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 2.7550649e-40]]
<NDArray 3x4 @cpu(0)>

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
<NDArray 3x4 @cpu(0)>

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
<NDArray 3x4 @cpu(0)>

[[-1.3064442   0.11287736 -2.6309927  -0.10713575]
 [ 0.31348416 -0.05735848 -1.1105995  -0.5765109 ]
 [-0.22899596  0.5796072   0.8124368   1.0448428 ]]
<NDArray 3x4 @cpu(0)>
[[-1.3064442   0.11287736 -2.6309927  -0.10713575]
 [ 0.31348416 -0.05735848 -1.1105995  -0.5765109 ]
 [-0.22899596  0.5796072   0.8124368   1.0448428 ]]
<class 'numpy.ndarray'>


In [3]:
# get array metadata/info

#shape and size
print(y.shape)
print(y.size)

(3, 4)
12


In [4]:
# ndarray Operations
print(x)
print(y)
#mult and addition
print(x + y) 
print(x*y) # element-wise multiplication
# exponentiation?

print(nd.exp(y))

# dot product

print(nd.dot(x, y.T)) #y is transposed, See https://en.wikipedia.org/wiki/Transpose


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
<NDArray 3x4 @cpu(0)>

[[-1.3064442   0.11287736 -2.6309927  -0.10713575]
 [ 0.31348416 -0.05735848 -1.1105995  -0.5765109 ]
 [-0.22899596  0.5796072   0.8124368   1.0448428 ]]
<NDArray 3x4 @cpu(0)>

[[-0.30644417  1.1128774  -1.6309927   0.8928642 ]
 [ 1.3134842   0.9426415  -0.11059952  0.4234891 ]
 [ 0.771004    1.5796072   1.8124368   2.0448427 ]]
<NDArray 3x4 @cpu(0)>

[[-1.3064442   0.11287736 -2.6309927  -0.10713575]
 [ 0.31348416 -0.05735848 -1.1105995  -0.5765109 ]
 [-0.22899596  0.5796072   0.8124368   1.0448428 ]]
<NDArray 3x4 @cpu(0)>

[[0.2707812  1.1194947  0.07200695 0.8984037 ]
 [1.3681839  0.94425553 0.32936144 0.5618553 ]
 [0.7953317  1.785337   2.2533925  2.8429518 ]]
<NDArray 3x4 @cpu(0)>

[[-3.9316952 -1.4309847  2.2078907]
 [-3.9316952 -1.4309847  2.2078907]
 [-3.9316952 -1.4309847  2.207891 ]]
<NDArray 3x3 @cpu(0)>


In [7]:
# in-place operations


#show how memory address changes

print('id(y):', id(y))
y = y + x
print('id(y):', id(y))

# use [:] syntax to prevent new address

print('id(y):', id(y))
y[:] = x + y
print('id(y):', id(y))

# event better with memory

nd.elemwise_add(x, y, out=y)

id(y): 4458715120
id(y): 4458683976
id(y): 4458683976
id(y): 4458683976



[[1.6935558  3.1128774  0.36900735 2.8928642 ]
 [3.3134842  2.9426415  1.8894005  2.423489  ]
 [2.771004   3.5796072  3.8124368  4.0448427 ]]
<NDArray 3x4 @cpu(0)>

In [8]:
# Slicing

print(x)
print(x[1:3])
print(x)
x[1,2] = 9.0
print(x)


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
<NDArray 3x4 @cpu(0)>

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
<NDArray 2x4 @cpu(0)>

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
<NDArray 3x4 @cpu(0)>

[[1. 1. 1. 1.]
 [1. 1. 9. 1.]
 [1. 1. 1. 1.]]
<NDArray 3x4 @cpu(0)>


In [9]:
# Broadcasting
# see http://gluon.mxnet.io/chapter01_crashcourse/ndarray.html#Broadcasting

x = nd.ones(shape=(3,3))
print('x = ', x)
y = nd.arange(3)
print('y = ', y)
print('x + y = ', x + y)

# Broadcast prefers to duplicate along the left most axis
# axis definition https://docs.scipy.org/doc/numpy-1.13.0/glossary.html
# http://gluon.mxnet.io/chapter01_crashcourse/linear-algebra.html#Length,-dimensionality,-and,-shape

y = y.reshape((3,1))
print('y = ', y)
print('x + y = ', x+y)

x =  
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
<NDArray 3x3 @cpu(0)>
y =  
[0. 1. 2.]
<NDArray 3 @cpu(0)>
x + y =  
[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]
<NDArray 3x3 @cpu(0)>
y =  
[[0.]
 [1.]
 [2.]]
<NDArray 3x1 @cpu(0)>
x + y =  
[[1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]]
<NDArray 3x3 @cpu(0)>


In [18]:
# context
#http://gluon.mxnet.io/chapter01_crashcourse/ndarray.html#Managing-context

# run on first gpu
# z = nd.ones(shape=(3,3), ctx=mx.gpu(0)) #doesn't work on osx without cuda and built from source
# run on first cpu
z = nd.ones(shape=(3,3), ctx=mx.cpu(0)) 
print(z)

# copy var and its context

x_cpu = x.copyto(mx.cpu(0))
print(x_cpu)

# show context

print(x_cpu.context)
print(z.context)

#!!! In order to perform an operation on two ndarrays x1 and x2, we need them both to live on the same context


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
<NDArray 3x3 @cpu(0)>

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
<NDArray 3x3 @cpu(0)>
cpu(0)
cpu(0)
