In [2]:
# http://gluon.mxnet.io/chapter01_crashcourse/ndarray.html
# https://mxnet.apache.org/tutorials/index.html
import mxnet as mx
from mxnet import nd
mx.random.seed(1)
# just looking at shapes


# empty array no init
x = nd.empty((3, 4))
print(x)

# empty but with with init

x = nd.zeros((3, 4), mx.cpu(0))
print(x)
x = nd.ones((3, 4), mx.cpu(0))
print(x)


# random with normal distribution and zero mean
print("\nshape = (3,4)");
y = nd.random_normal(0, 1, shape=(3, 4))
print(y);

print("\nshape = 3");
# random with normal distribution and zero mean - different shape
y2 = nd.random_normal(0, 1, shape=3)
print(y2);

print("\nshape = (3,1)");
# random with normal distribution and zero mean - different shape #2
y3 = nd.random_normal(0, 1, shape=(3,1))
print(y3);

print("\nshape = (1,3)");
# random with normal distribution and zero mean - different shape #3
y4 = nd.random_normal(0, 1, shape=(1,3))
print(y4);
print();

# convert ndarray to numpy

yn = y.asnumpy()
print(yn)
print(type(yn))




[[  0.00000000e+00   1.58456325e+29   0.00000000e+00   1.58456325e+29]
 [  2.09444955e-33   1.40129846e-45   2.13535308e-33   1.40129846e-45]
 [  2.35904965e-33   1.40129846e-45   2.11752083e-33   1.40129846e-45]]
<NDArray 3x4 @cpu(0)>

[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
<NDArray 3x4 @cpu(0)>

[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]
<NDArray 3x4 @cpu(0)>

shape = (3,4)

[[ 0.03629481 -0.49024421 -0.95017916  0.03751944]
 [-0.72984636 -2.04010558  1.482131    1.04082799]
 [-0.45256865  0.31160426 -0.83673781 -0.78830057]]
<NDArray 3x4 @cpu(0)>

shape = 3

[ 0.12664476 -0.17841923  0.76479203]
<NDArray 3 @cpu(0)>

shape = (3,1)

[[-0.21776067]
 [ 2.22578788]
 [-0.68832648]]
<NDArray 3x1 @cpu(0)>

shape = (1,3)

[[ 0.84155577 -0.61584121  0.01961165]]
<NDArray 1x3 @cpu(0)>

[[ 0.03629481 -0.49024421 -0.95017916  0.03751944]
 [-0.72984636 -2.04010558  1.482131    1.04082799]
 [-0.45256865  0.31160426 -0.83673781 -0.78830057]]
<class 'numpy.ndarray'

/usr/local/lib/python3.6/site-packages/mxnet/optimizer.py:136: UserWarning: WARNING: New optimizer mxnet.optimizer.NAG is overriding existing optimizer mxnet.optimizer.NAG
  Optimizer.opt_registry[name].__name__))


In [3]:
# get array metadata/info

#shape and size
print(y.shape)
print(y.size)

(3, 4)
12


In [11]:
# ndarray Operations
print(x)
print(y)
z = nd.ones(shape=(4,), ctx=mx.cpu(0))+4 
print(z)
#mult and addition
print(x + y) 
print(x*y) # element-wise multiplication
# addition with different shapes
print(y + z) 

# max
print("\n y max axis 1")
print(nd.max(y,axis=1))
print("\n y max axis 0")
print(nd.max(y,axis=0))

# exponentiation?
print("\n\n y exponentiation \n")
print(nd.exp(y))

# dot product
print("\ny orignal\n")
print(y)
print("\ny is transposed\n")
print(y.T)

print("\nMultiplication of\n")
print(x,y.T)

print("\nDot Product of x and y.T == \n")
print(nd.dot(x, y.T)) #y is transposed, See https://en.wikipedia.org/wiki/Transpose



[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]
<NDArray 3x4 @cpu(0)>

[[ 0.03629481 -0.49024421 -0.95017916  0.03751944]
 [-0.72984636 -2.04010558  1.482131    1.04082799]
 [-0.45256865  0.31160426 -0.83673781 -0.78830057]]
<NDArray 3x4 @cpu(0)>

[ 5.  5.  5.  5.]
<NDArray 4 @cpu(0)>

[[ 1.03629482  0.50975579  0.04982084  1.03751945]
 [ 0.27015364 -1.04010558  2.482131    2.04082799]
 [ 0.54743135  1.31160426  0.16326219  0.21169943]]
<NDArray 3x4 @cpu(0)>

[[ 0.03629481 -0.49024421 -0.95017916  0.03751944]
 [-0.72984636 -2.04010558  1.482131    1.04082799]
 [-0.45256865  0.31160426 -0.83673781 -0.78830057]]
<NDArray 3x4 @cpu(0)>

[[ 5.03629494  4.50975561  4.0498209   5.03751945]
 [ 4.27015352  2.95989442  6.482131    6.04082775]
 [ 4.54743147  5.3116045   4.16326237  4.21169949]]
<NDArray 3x4 @cpu(0)>

 y max axis 1

[ 0.03751944  1.482131    0.31160426]
<NDArray 3 @cpu(0)>

 y max axis 0

[ 0.03629481  0.31160426  1.482131    1.04082799]
<NDArray 4 @cpu(0)>


 y exponen

In [16]:
# data sum
data = nd.array([[[1,2],[2,3],[1,3]],
        [[1,4],[4,3],[5,2]],
        [[7,1],[7,2],[7,3]]])
print(data.shape)
print(data)
print("\naxis 2")
print(nd.sum(data, axis=2))
print("\naxis 1")
print(nd.sum(data, axis=1))
print("\naxis 0")
print(nd.sum(data, axis=0))
print("\naxis NULL")
print(nd.sum(data))

(3, 3, 2)

[[[ 1.  2.]
  [ 2.  3.]
  [ 1.  3.]]

 [[ 1.  4.]
  [ 4.  3.]
  [ 5.  2.]]

 [[ 7.  1.]
  [ 7.  2.]
  [ 7.  3.]]]
<NDArray 3x3x2 @cpu(0)>

axis 2

[[  3.   5.   4.]
 [  5.   7.   7.]
 [  8.   9.  10.]]
<NDArray 3x3 @cpu(0)>

axis 1

[[  4.   8.]
 [ 10.   9.]
 [ 21.   6.]]
<NDArray 3x2 @cpu(0)>

axis 0

[[  9.   7.]
 [ 13.   8.]
 [ 13.   8.]]
<NDArray 3x2 @cpu(0)>

axis NULL

[ 58.]
<NDArray 1 @cpu(0)>


In [7]:
# in-place operations


#show how memory address changes

print('id(y):', id(y))
y = y + x
print('id(y):', id(y))

# use [:] syntax to prevent new address

print('id(y):', id(y))
y[:] = x + y
print('id(y):', id(y))

# event better with memory

nd.elemwise_add(x, y, out=y)

id(y): 4458715120
id(y): 4458683976
id(y): 4458683976
id(y): 4458683976



[[1.6935558  3.1128774  0.36900735 2.8928642 ]
 [3.3134842  2.9426415  1.8894005  2.423489  ]
 [2.771004   3.5796072  3.8124368  4.0448427 ]]
<NDArray 3x4 @cpu(0)>

In [8]:
# Slicing

print(x)
print(x[1:3])
print(x)
x[1,2] = 9.0
print(x)


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
<NDArray 3x4 @cpu(0)>

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
<NDArray 2x4 @cpu(0)>

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
<NDArray 3x4 @cpu(0)>

[[1. 1. 1. 1.]
 [1. 1. 9. 1.]
 [1. 1. 1. 1.]]
<NDArray 3x4 @cpu(0)>


In [9]:
# Broadcasting
# see http://gluon.mxnet.io/chapter01_crashcourse/ndarray.html#Broadcasting

x = nd.ones(shape=(3,3))
print('x = ', x)
y = nd.arange(3)
print('y = ', y)
print('x + y = ', x + y)

# Broadcast prefers to duplicate along the left most axis
# axis definition https://docs.scipy.org/doc/numpy-1.13.0/glossary.html
# http://gluon.mxnet.io/chapter01_crashcourse/linear-algebra.html#Length,-dimensionality,-and,-shape

y = y.reshape((3,1))
print('y = ', y)
print('x + y = ', x+y)

x =  
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
<NDArray 3x3 @cpu(0)>
y =  
[0. 1. 2.]
<NDArray 3 @cpu(0)>
x + y =  
[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]
<NDArray 3x3 @cpu(0)>
y =  
[[0.]
 [1.]
 [2.]]
<NDArray 3x1 @cpu(0)>
x + y =  
[[1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]]
<NDArray 3x3 @cpu(0)>


In [18]:
# context
#http://gluon.mxnet.io/chapter01_crashcourse/ndarray.html#Managing-context

# run on first gpu
# z = nd.ones(shape=(3,3), ctx=mx.gpu(0)) #doesn't work on osx without cuda and built from source
# run on first cpu
z = nd.ones(shape=(3,3), ctx=mx.cpu(0)) 
print(z)

# copy var and its context

x_cpu = x.copyto(mx.cpu(0))
print(x_cpu)

# show context

print(x_cpu.context)
print(z.context)

#!!! In order to perform an operation on two ndarrays x1 and x2, we need them both to live on the same context


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
<NDArray 3x3 @cpu(0)>

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
<NDArray 3x3 @cpu(0)>
cpu(0)
cpu(0)
